/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_snmill_evs_EvsDecoderJni */

#ifndef _Included_com_snmill_evs_EvsDecoderJni
#define _Included_com_snmill_evs_EvsDecoderJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_snmill_evs_EvsDecoderJni
 * Method:    dCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_snmill_evs_EvsDecoderJni_dCreate
  (JNIEnv *, jclass);

/*
 * Class:     com_snmill_evs_EvsDecoderJni
 * Method:    dDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_snmill_evs_EvsDecoderJni_dDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
