/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_snmill_evs_EvsEncoderJni */

#ifndef _Included_com_snmill_evs_EvsEncoderJni
#define _Included_com_snmill_evs_EvsEncoderJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_snmill_evs_EvsEncoderJni
 * Method:    eCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_snmill_evs_EvsEncoderJni_eCreate
  (JNIEnv *, jclass);

/*
 * Class:     com_snmill_evs_EvsEncoderJni
 * Method:    eDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_snmill_evs_EvsEncoderJni_eDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
